[2025-03-19T04:48:53.282+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-19T04:48:53.301+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: github_etl.transform manual__2025-03-19T04:48:38.241154+00:00 [queued]>
[2025-03-19T04:48:53.307+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: github_etl.transform manual__2025-03-19T04:48:38.241154+00:00 [queued]>
[2025-03-19T04:48:53.307+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-03-19T04:48:53.319+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform> on 2025-03-19 04:48:38.241154+00:00
[2025-03-19T04:48:53.322+0000] {standard_task_runner.py:63} INFO - Started process 5995 to run task
[2025-03-19T04:48:53.324+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'github_etl', 'transform', 'manual__2025-03-19T04:48:38.241154+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/github_etl.py', '--cfg-path', '/tmp/tmp2vbw7q1j']
[2025-03-19T04:48:53.326+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask transform
[2025-03-19T04:48:53.361+0000] {task_command.py:426} INFO - Running <TaskInstance: github_etl.transform manual__2025-03-19T04:48:38.241154+00:00 [running]> on host cc427449653e
[2025-03-19T04:48:53.509+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='github_etl' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2025-03-19T04:48:38.241154+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-19T04:48:38.241154+00:00'
[2025-03-19T04:48:53.511+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-19T04:49:00.588+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-19T04:49:00.590+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/github_etl.py", line 24, in transform
    df_filtered = df.select("id", "type", "actor.login", "repo.name", "created_at")
  File "/home/airflow/.local/lib/python3.10/site-packages/pyspark/sql/dataframe.py", line 3229, in select
    jdf = self._jdf.select(self._jcols(*cols))
  File "/home/airflow/.local/lib/python3.10/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
  File "/home/airflow/.local/lib/python3.10/site-packages/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.AnalysisException: [INVALID_EXTRACT_BASE_FIELD_TYPE] Can't extract a value from "actor". Need a complex type [STRUCT, ARRAY, MAP] but got "STRING".
[2025-03-19T04:49:00.606+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=github_etl, task_id=transform, run_id=manual__2025-03-19T04:48:38.241154+00:00, execution_date=20250319T044838, start_date=20250319T044853, end_date=20250319T044900
[2025-03-19T04:49:00.617+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task transform ([INVALID_EXTRACT_BASE_FIELD_TYPE] Can't extract a value from "actor". Need a complex type [STRUCT, ARRAY, MAP] but got "STRING".; 5995)
[2025-03-19T04:49:00.634+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-03-19T04:49:00.649+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-19T04:49:00.656+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
